apiVersion: v2
description: Elastic Beats managed by the ECK operator
icon: https://helm.elastic.co/icons/beats.png
kubeVersion: '>= 1.20.0-0'
name: eck-beats
type: application
version: 0.1.0
appVersion: "6.8.0"