apiVersion: v2
description: Elastic APM Server managed by the ECK operator
icon: https://helm.elastic.co/icons/apm.png
kubeVersion: '>= 1.21.0-0'
name: eck-apm-server
type: application
version: 0.1.0
appVersion: "6.8.0"
