apiVersion: v2
description: Kibana managed by the ECK operator
icon: https://helm.elastic.co/icons/kibana.png
kubeVersion: '>= 1.21.0-0'
name: eck-kibana
type: application
version: 0.1.0
appVersion: 6.8.0