apiVersion: v2
description: Elastic Enterprise Search managed by the ECK operator
icon: https://github.com/elastic/ent-search/blob/main/public/app-search-favicon-196x196.png
kubeVersion: '>= 1.21.0-0'
name: eck-enterprise-search
type: application
version: 0.1.0
appVersion: "6.8.0"