apiVersion: v2
description: Logstash managed by the ECK operator
icon: https://helm.elastic.co/icons/logstash.png
kubeVersion: '>= 1.21.0-0'
name: eck-logstash
type: application
version: 0.1.0
appVersion: "6.8.0"