apiVersion: v2
kubeVersion: ">= 1.21.0-0"
name: eck-elasticsearch
description: Elasticsearch managed by the ECK operator
type: application
version: 0.1.0-SNAPSHOT
appVersion: "6.8.0"
sources:
  - https://github.com/Octodet/eck-stack-helm
icon: https://helm.elastic.co/icons/elasticsearch.png